# Generated by Django 2.0 on 2020-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='last_change_time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
